[package]
name = "ergo-lib-python"
version = "0.28.0"
license = "CC0-1.0"
authors = ["Kamal Ahmad <kamalahmad22@pm.me>"]
edition.workspace = true
repository.workspace = true
description = "Python bindings for ergo-lib"

[lib]
name = "ergo_lib_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
ergo-lib = { workspace = true }
